services:
  postgres-for-skycastle:
    image: postgres:17-alpine
    container_name: postgres-for-skycastle
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skycastle
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
