services:
  postgres-for-skycastle:
    image: postgres:17-alpine
    container_name: postgres-for-skycastle
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skycastle
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  skycastle:
    build: .
    image: skycastle
    ports:
        - 8001:8001
    restart: always

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: influx-user
      DOCKER_INFLUXDB_INIT_PASSWORD: influx-password
      DOCKER_INFLUXDB_INIT_ORG: influx-org
      DOCKER_INFLUXDB_INIT_BUCKET: influx-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: influx-yuyu-token
    restart: always

  grafana:
    ports:
        - 3001:3000
    restart: always
    volumes:
        - grafana-volume:/var/lib/grafana
    image: grafana/grafana

volumes:
  grafana-volume:
  influxdb-data:
  influxdb-config:
  postgres-data:
