# Generated by Django 5.1.2 on 2024-11-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_servo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servo',
        ),
    ]
